services:
  db:
    image: mysql:8.0
    container_name: macrofit-mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=macrofit_db
      - MYSQL_USER=admin_macrofit
      - MYSQL_PASSWORD=password123
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - macrofit-net
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  macrofit-usuarios:
    build: .
    container_name: macrofit-usuarios-api
    ports:
      - "80:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://macrofit-mysql-db:3306/macrofit_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=admin_macrofit
      - SPRING_DATASOURCE_PASSWORD=password123
      - DB_HOST=macrofit-mysql-db
      - DB_PORT=3306
      - DB_NAME=macrofit_db
      - DB_USER=admin_macrofit
      - DB_PASSWORD=password123
      - API_KEY=2cc1d2610130469cb33eed6cc81abd0e
      - API_URL=https://api.spoonacular.com/recipes/complexSearch
    depends_on:
      db:
        condition: service_healthy
    networks:
      - macrofit-net
    restart: always

volumes:
  mysql_data:
    driver: local

networks:
  macrofit-net:
    driver: bridge